//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.SendMailCalendar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailAccountModel
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ServerProviderId { get; set; }
        public string SenderName { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Signature { get; set; }
        public Nullable<bool> IsSender { get; set; }
    }
}
