//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.SendMailCalendar.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailServerProviderModel
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Protocol { get; set; }
        public string IncomingHost { get; set; }
        public Nullable<int> IncomingPort { get; set; }
        public string OutgoingHost { get; set; }
        public int OutgoingPort { get; set; }
    }
}
