//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.SendMailCalendar.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SendMailCalendarEntities : DbContext
    {
        public SendMailCalendarEntities()
            : base("name=SendMailCalendarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProfileModel> ProfileModels { get; set; }
        public virtual DbSet<CampaignModel> CampaignModels { get; set; }
        public virtual DbSet<ContentModel> ContentModels { get; set; }
        public virtual DbSet<EmailAccountModel> EmailAccountModels { get; set; }
        public virtual DbSet<MailServerProviderModel> MailServerProviderModels { get; set; }
        public virtual DbSet<MemberOfTargetGroupModel> MemberOfTargetGroupModels { get; set; }
        public virtual DbSet<SendMailCalendarModel> SendMailCalendarModels { get; set; }
        public virtual DbSet<TargetGroupModel> TargetGroupModels { get; set; }
        public virtual DbSet<CatalogModel> CatalogModels { get; set; }
        public virtual DbSet<Unfollow> Unfollows { get; set; }
    }
}
