//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessoryPriceModel
    {
        public System.Guid AccessoryPriceId { get; set; }
        public string SAPCode { get; set; }
        public string AccessoryCode { get; set; }
        public string ConditionType { get; set; }
        public string PriceGroup { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UOM { get; set; }
        public Nullable<System.DateTime> EffectedFromDate { get; set; }
        public Nullable<System.DateTime> EffectedToDate { get; set; }
        public Nullable<bool> Actived { get; set; }
    }
}
