//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessorySaleOrderModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessorySaleOrderModel()
        {
            this.AccessorySaleOrderDetailModel = new HashSet<AccessorySaleOrderDetailModel>();
        }
    
        public System.Guid AccessorySaleOrderId { get; set; }
        public string AccessorySaleOrderCode { get; set; }
        public Nullable<System.Guid> AccessorySellTypeId { get; set; }
        public string SaleOrg { get; set; }
        public string ConsultEmployeeCode { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> WardId { get; set; }
        public string CustomerAddress { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> IdentityDate { get; set; }
        public string IdentityPlace { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string TaxCode { get; set; }
        public Nullable<System.Guid> VehicleId { get; set; }
        public string LicensePlate { get; set; }
        public string SerialNumber { get; set; }
        public string EngineNumber { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string ProfitCenterName { get; set; }
        public string ProductHierarchyName { get; set; }
        public string MaterialGroupName { get; set; }
        public string LaborName { get; set; }
        public string MaterialFreightGroupName { get; set; }
        public string ExternalMaterialGroupName { get; set; }
        public string TemperatureConditionName { get; set; }
        public string ContainerRequirementName { get; set; }
        public Nullable<decimal> CurrentKilometers { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string EmployeeCode { get; set; }
        public int GeneratedCode { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsLayHang { get; set; }
        public Nullable<bool> IsXacNhan { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> TransferCreatedDate { get; set; }
        public string TransferCreatedUser { get; set; }
        public Nullable<System.DateTime> CompleteCreatedDate { get; set; }
        public string CompleteCreatedUser { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelUser { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string DiscountNote { get; set; }
        public string CancelNote { get; set; }
    
        public virtual CustomerModel CustomerModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessorySaleOrderDetailModel> AccessorySaleOrderDetailModel { get; set; }
        public virtual VehicleInfoModel VehicleInfoModel { get; set; }
    }
}
