//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessorySaleOrderDetailModel
    {
        public System.Guid AccessorySaleOrderDetailId { get; set; }
        public Nullable<System.Guid> AccessorySaleOrderId { get; set; }
        public Nullable<System.Guid> AccessorySellTypeId { get; set; }
        public string AccessoryCode { get; set; }
        public string AccessoryName { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Plant { get; set; }
        public string WarehouseCode { get; set; }
        public string Location { get; set; }
        public string Note { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual AccessorySaleOrderModel AccessorySaleOrderModel { get; set; }
    }
}
