//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountModel()
        {
            this.ApplicationLog = new HashSet<ApplicationLog>();
            this.NotificationAccountMappingModel = new HashSet<NotificationAccountMappingModel>();
            this.ContentModel = new HashSet<ContentModel>();
            this.ContentModel1 = new HashSet<ContentModel>();
            this.TargetGroupModel = new HashSet<TargetGroupModel>();
            this.TargetGroupModel1 = new HashSet<TargetGroupModel>();
            this.TemplateAndGiftCampaignModel = new HashSet<TemplateAndGiftCampaignModel>();
            this.TemplateAndGiftCampaignModel1 = new HashSet<TemplateAndGiftCampaignModel>();
            this.TemplateAndGiftMemberAddressModel = new HashSet<TemplateAndGiftMemberAddressModel>();
            this.TemplateAndGiftMemberAddressModel1 = new HashSet<TemplateAndGiftMemberAddressModel>();
            this.TemplateAndGiftTargetGroupModel = new HashSet<TemplateAndGiftTargetGroupModel>();
            this.TemplateAndGiftTargetGroupModel1 = new HashSet<TemplateAndGiftTargetGroupModel>();
            this.FavoriteReportModel = new HashSet<FavoriteReportModel>();
            this.QuestionBankModel = new HashSet<QuestionBankModel>();
            this.QuestionBankModel1 = new HashSet<QuestionBankModel>();
            this.StockTransferRequestModel = new HashSet<StockTransferRequestModel>();
            this.StockTransferRequestModel1 = new HashSet<StockTransferRequestModel>();
            this.StockTransferRequestModel2 = new HashSet<StockTransferRequestModel>();
            this.RolesModel = new HashSet<RolesModel>();
            this.StoreModel = new HashSet<StoreModel>();
        }
    
        public System.Guid AccountId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<bool> isShowChoseModule { get; set; }
        public Nullable<bool> isViewTotal { get; set; }
        public Nullable<bool> isViewByWarehouse { get; set; }
        public Nullable<bool> isReceiveNotification { get; set; }
        public string TaskFilterCode { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string OneSignalWebId { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<bool> isShowDashboard { get; set; }
        public Nullable<bool> isViewByStore { get; set; }
        public Nullable<bool> isCreatePrivateTask { get; set; }
        public Nullable<bool> isViewRevenue { get; set; }
        public string ViewPermission { get; set; }
        public Nullable<bool> isViewOpportunity { get; set; }
        public string GoogleCalendarId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationLog> ApplicationLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationAccountMappingModel> NotificationAccountMappingModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentModel> ContentModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentModel> ContentModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetGroupModel> TargetGroupModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetGroupModel> TargetGroupModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftCampaignModel> TemplateAndGiftCampaignModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftCampaignModel> TemplateAndGiftCampaignModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftMemberAddressModel> TemplateAndGiftMemberAddressModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftMemberAddressModel> TemplateAndGiftMemberAddressModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftTargetGroupModel> TemplateAndGiftTargetGroupModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftTargetGroupModel> TemplateAndGiftTargetGroupModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteReportModel> FavoriteReportModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionBankModel> QuestionBankModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionBankModel> QuestionBankModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransferRequestModel> StockTransferRequestModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransferRequestModel> StockTransferRequestModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransferRequestModel> StockTransferRequestModel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolesModel> RolesModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreModel> StoreModel { get; set; }
    }
}
