//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIModel
    {
        public string Token { get; set; }
        public string Key { get; set; }
        public Nullable<bool> isAllowedToBooking { get; set; }
        public Nullable<bool> isRequiredLogin { get; set; }
        public Nullable<bool> isReceiveInCurrentDay { get; set; }
    }
}
