//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public System.Guid ApplicationLogId { get; set; }
        public System.DateTime PerformedAt { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> PerformedBy_AccountId { get; set; }
    
        public virtual AccountModel AccountModel { get; set; }
    }
}
