//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentModel
    {
        public System.Guid AppointmentId { get; set; }
        public Nullable<System.Guid> PrimaryContactId { get; set; }
        public string CustomerClassCode { get; set; }
        public string CategoryCode { get; set; }
        public string ShowroomCode { get; set; }
        public string SaleEmployeeCode { get; set; }
        public string ChannelCode { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Requirement { get; set; }
        public Nullable<bool> isSentSMS { get; set; }
        public string SaleEmployeeOffer { get; set; }
        public Nullable<bool> isVisitCabinetPro { get; set; }
        public string VisitCabinetProRequest { get; set; }
    }
}
