//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoConditionModel
    {
        public System.Guid AutoConditionId { get; set; }
        public Nullable<System.Guid> StatusTransitionId { get; set; }
        public string AdditionalSQLText { get; set; }
        public string ConditionType { get; set; }
        public string Field { get; set; }
        public string ComparisonType { get; set; }
        public string ValueType { get; set; }
        public string Value { get; set; }
        public string SQLText { get; set; }
        public Nullable<int> OrderIndex { get; set; }
    }
}
