//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangTinModel
    {
        public System.Guid NewsId { get; set; }
        public int NewsCode { get; set; }
        public Nullable<System.Guid> NewsCategoryId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> isShowOnMobile { get; set; }
        public Nullable<bool> isShowOnWeb { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string Detail { get; set; }
    }
}
