//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerModel
    {
        public System.Guid BannerId { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
