//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingModel
    {
        public System.Guid BookingModelId { get; set; }
        public long BookingCode { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public string Plate { get; set; }
        public string BikeModel { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.TimeSpan> BookingTime { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsConfirm { get; set; }
        public Nullable<bool> IsCreatedServiceOrder { get; set; }
    }
}
