//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerModel
    {
        public System.Guid CareerId { get; set; }
        public string CareerCode { get; set; }
        public string CareerName { get; set; }
        public Nullable<bool> Actived { get; set; }
    }
}
