//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogTypeModel
    {
        public string CatalogTypeCode { get; set; }
        public string CatalogTypeName { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string CategoryType { get; set; }
        public string Note { get; set; }
    }
}
