//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeDataLogModel
    {
        public System.Guid LogId { get; set; }
        public string TableName { get; set; }
        public Nullable<System.Guid> PrimaryKey { get; set; }
        public string FieldName { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
