//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOutModel
    {
        public System.Guid CheckInOutId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public string CheckInLat { get; set; }
        public string CheckInLng { get; set; }
        public Nullable<decimal> CheckInDistance { get; set; }
        public Nullable<System.Guid> CheckInBy { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public string CheckOutLat { get; set; }
        public string CheckOutLng { get; set; }
        public Nullable<decimal> CheckOutDistance { get; set; }
        public Nullable<System.Guid> CheckOutBy { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
    }
}
