//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckingTimesNotificationModel
    {
        public System.Guid CheckingTimesId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string CustomerCode { get; set; }
        public string CheckingTimesDescription { get; set; }
        public Nullable<bool> isRead { get; set; }
    }
}
