//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorProductModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColorProductModel()
        {
            this.ImageProductModel = new HashSet<ImageProductModel>();
        }
    
        public System.Guid ColorProductId { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<System.Guid> StyleId { get; set; }
        public Nullable<System.Guid> MainColorId { get; set; }
    
        public virtual ProductModel ProductModel { get; set; }
        public virtual StyleModel StyleModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProductModel> ImageProductModel { get; set; }
    }
}
