//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTastesModel
    {
        public System.Guid CustomerTasteId { get; set; }
        public string ERPProductCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.Guid> AppointmentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
