//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGiftModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerGiftModel()
        {
            this.CustomerGiftDetailModel = new HashSet<CustomerGiftDetailModel>();
        }
    
        public System.Guid GiftId { get; set; }
        public string GiftCode { get; set; }
        public string GiftName { get; set; }
        public Nullable<System.DateTime> EffectFromDate { get; set; }
        public Nullable<System.DateTime> EffectToDate { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerGiftDetailModel> CustomerGiftDetailModel { get; set; }
    }
}
