//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerGiftDetailModel
    {
        public System.Guid GiftId { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<bool> isRead { get; set; }
    
        public virtual CustomerModel CustomerModel { get; set; }
        public virtual CustomerGiftModel CustomerGiftModel { get; set; }
    }
}
