//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerModel()
        {
            this.AccessorySaleOrderModel = new HashSet<AccessorySaleOrderModel>();
            this.CustomerGiftDetailModel = new HashSet<CustomerGiftDetailModel>();
            this.SaleOrderMasterModel = new HashSet<SaleOrderMasterModel>();
            this.ServiceOrderModel = new HashSet<ServiceOrderModel>();
        }
    
        public System.Guid CustomerId { get; set; }
        public string SaleOrg { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string FullName { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> IdentityDate { get; set; }
        public string IdentityPlace { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> WardId { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string EmailAddress { get; set; }
        public string Fax { get; set; }
        public Nullable<System.Guid> Career { get; set; }
        public string TaxCode { get; set; }
        public string IdentityUrl { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int GeneratedCode { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string IdentityUrl2 { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessorySaleOrderModel> AccessorySaleOrderModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerGiftDetailModel> CustomerGiftDetailModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderMasterModel> SaleOrderMasterModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderModel> ServiceOrderModel { get; set; }
    }
}
