//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAS_EMAILTEMPLATE
    {
        public decimal ID { get; set; }
        public string FROM { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string EMAILPASS { get; set; }
        public string TO { get; set; }
        public string CMPCD { get; set; }
    }
}
