//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDateModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DimDateModel()
        {
            this.DeliveryDetailModel = new HashSet<DeliveryDetailModel>();
            this.StockReceivingDetailModel = new HashSet<StockReceivingDetailModel>();
            this.TransferDetailModel = new HashSet<TransferDetailModel>();
        }
    
        public int DateKey { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FullDateUK { get; set; }
        public string FullDateUSA { get; set; }
        public string DayOfMonth { get; set; }
        public string DaySuffix { get; set; }
        public string DayName { get; set; }
        public string DayOfWeekUSA { get; set; }
        public string DayOfWeekUK { get; set; }
        public string DayOfWeekInMonth { get; set; }
        public string DayOfWeekInYear { get; set; }
        public string DayOfQuarter { get; set; }
        public string DayOfYear { get; set; }
        public string WeekOfMonth { get; set; }
        public string WeekOfQuarter { get; set; }
        public string WeekOfYear { get; set; }
        public string Month { get; set; }
        public string MonthName { get; set; }
        public string MonthOfQuarter { get; set; }
        public string Quarter { get; set; }
        public string QuarterName { get; set; }
        public string Year { get; set; }
        public string YearName { get; set; }
        public string MonthYear { get; set; }
        public string MMYYYY { get; set; }
        public Nullable<System.DateTime> FirstDayOfMonth { get; set; }
        public Nullable<System.DateTime> LastDayOfMonth { get; set; }
        public Nullable<System.DateTime> FirstDayOfQuarter { get; set; }
        public Nullable<System.DateTime> LastDayOfQuarter { get; set; }
        public Nullable<System.DateTime> FirstDayOfYear { get; set; }
        public Nullable<System.DateTime> LastDayOfYear { get; set; }
        public Nullable<bool> IsHolidayUSA { get; set; }
        public Nullable<bool> IsWeekday { get; set; }
        public string HolidayUSA { get; set; }
        public Nullable<bool> IsHolidayUK { get; set; }
        public string HolidayUK { get; set; }
        public string FiscalDayOfYear { get; set; }
        public string FiscalWeekOfYear { get; set; }
        public string FiscalMonth { get; set; }
        public string FiscalQuarter { get; set; }
        public string FiscalQuarterName { get; set; }
        public string FiscalYear { get; set; }
        public string FiscalYearName { get; set; }
        public string FiscalMonthYear { get; set; }
        public string FiscalMMYYYY { get; set; }
        public Nullable<System.DateTime> FiscalFirstDayOfMonth { get; set; }
        public Nullable<System.DateTime> FiscalLastDayOfMonth { get; set; }
        public Nullable<System.DateTime> FiscalFirstDayOfQuarter { get; set; }
        public Nullable<System.DateTime> FiscalLastDayOfQuarter { get; set; }
        public Nullable<System.DateTime> FiscalFirstDayOfYear { get; set; }
        public Nullable<System.DateTime> FiscalLastDayOfYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryDetailModel> DeliveryDetailModel { get; set; }
        public virtual DimDateModel DimDateModel1 { get; set; }
        public virtual DimDateModel DimDateModel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReceivingDetailModel> StockReceivingDetailModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferDetailModel> TransferDetailModel { get; set; }
    }
}
