//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictModel
    {
        public System.Guid DistrictId { get; set; }
        public System.Guid ProvinceId { get; set; }
        public string Appellation { get; set; }
        public string DistrictName { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<decimal> RegisterVAT { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public bool Actived { get; set; }
        public string VehicleRegistrationSignature { get; set; }
    }
}
