//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateConfigModel
    {
        public System.Guid EmailTemplateConfigId { get; set; }
        public string EmailTemplateType { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string EmailFrom { get; set; }
        public string EmailSender { get; set; }
        public string EmailHost { get; set; }
        public Nullable<int> EmailPort { get; set; }
        public Nullable<bool> EmailEnableSsl { get; set; }
        public string EmailAccount { get; set; }
        public string EmailPassword { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
