//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfig
    {
        public System.Guid EmailConfigId { get; set; }
        public string Email { get; set; }
        public string SmtpServer { get; set; }
        public string SmtpPort { get; set; }
        public Nullable<bool> EnableSsl { get; set; }
        public string SmtpMailFrom { get; set; }
        public string SmtpUser { get; set; }
        public string SmtpPassword { get; set; }
        public string ToEmail { get; set; }
        public string CCMail { get; set; }
        public string BCCMail { get; set; }
        public string EmailTitle { get; set; }
        public string EmailContent { get; set; }
    }
}
