//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceCheckInOutModel
    {
        public string FaceId { get; set; }
        public string PersonName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> CheckinTime { get; set; }
        public string AliasID { get; set; }
        public string PlaceID { get; set; }
        public string PersonID { get; set; }
        public string avatar { get; set; }
        public string Place { get; set; }
        public Nullable<int> type { get; set; }
        public string DeviceID { get; set; }
        public string DeviceName { get; set; }
    }
}
