//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttachmentModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileAttachmentModel()
        {
            this.Comment_File_Mapping = new HashSet<Comment_File_Mapping>();
            this.Profile_File_Mapping = new HashSet<Profile_File_Mapping>();
            this.Task_File_Mapping = new HashSet<Task_File_Mapping>();
        }
    
        public System.Guid FileAttachmentId { get; set; }
        public System.Guid ObjectId { get; set; }
        public string FileAttachmentCode { get; set; }
        public string FileAttachmentName { get; set; }
        public string FileExtention { get; set; }
        public string FileUrl { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public string FileType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_File_Mapping> Comment_File_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_File_Mapping> Profile_File_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_File_Mapping> Task_File_Mapping { get; set; }
    }
}
