//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixingTypeModel
    {
        public System.Guid FixingTypeId { get; set; }
        public string FixingTypeCode { get; set; }
        public string FixingTypeName { get; set; }
        public Nullable<System.Guid> ServiceFlagId { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<bool> IsTinhTien { get; set; }
        public Nullable<bool> IsBaoHanh { get; set; }
        public Nullable<bool> IsKhieuNai { get; set; }
        public Nullable<bool> IsAccessory { get; set; }
    }
}
