//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialPropertiesModel
    {
        public System.Guid PropertiesId { get; set; }
        public string MaterialCode { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}
