//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuModel()
        {
            this.MobileScreenModel = new HashSet<MobileScreenModel>();
            this.PageModel = new HashSet<PageModel>();
        }
    
        public System.Guid MenuId { get; set; }
        public Nullable<System.Guid> ModuleId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileScreenModel> MobileScreenModel { get; set; }
        public virtual ModuleModel ModuleModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageModel> PageModel { get; set; }
    }
}
