//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileScreenModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MobileScreenModel()
        {
            this.MobileScreenPermissionModel = new HashSet<MobileScreenPermissionModel>();
            this.FunctionModel = new HashSet<FunctionModel>();
        }
    
        public System.Guid MobileScreenId { get; set; }
        public string ScreenName { get; set; }
        public string ScreenCode { get; set; }
        public Nullable<System.Guid> MenuId { get; set; }
        public string IconType { get; set; }
        public string IconName { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> isSystem { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<bool> isCreated { get; set; }
        public Nullable<bool> isReporter { get; set; }
        public Nullable<bool> isAssignee { get; set; }
    
        public virtual MenuModel MenuModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileScreenPermissionModel> MobileScreenPermissionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunctionModel> FunctionModel { get; set; }
    }
}
