//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleModel()
        {
            this.MenuModel = new HashSet<MenuModel>();
        }
    
        public System.Guid ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string Url { get; set; }
        public Nullable<bool> isSystemModule { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Icon { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuModel> MenuModel { get; set; }
    }
}
