//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PageModel()
        {
            this.FavoriteReportModel = new HashSet<FavoriteReportModel>();
            this.PagePermissionModel = new HashSet<PagePermissionModel>();
            this.FunctionModel = new HashSet<FunctionModel>();
        }
    
        public System.Guid PageId { get; set; }
        public string PageName { get; set; }
        public string PageUrl { get; set; }
        public Nullable<System.Guid> MenuId { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Visiable { get; set; }
        public Nullable<bool> isSystem { get; set; }
        public bool Actived { get; set; }
        public string Parameter { get; set; }
        public string Color { get; set; }
    
        public virtual MenuModel MenuModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteReportModel> FavoriteReportModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagePermissionModel> PagePermissionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunctionModel> FunctionModel { get; set; }
    }
}
