//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerModel
    {
        public System.Guid PartnerId { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public string PartnerType { get; set; }
        public Nullable<System.Guid> PartnerProfileId { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    
        public virtual ProfileModel ProfileModel { get; set; }
        public virtual ProfileModel ProfileModel1 { get; set; }
    }
}
