//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodicallyCheckingModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeriodicallyCheckingModel()
        {
            this.ProductModel = new HashSet<ProductModel>();
        }
    
        public System.Guid PeriodicallyCheckingId { get; set; }
        public string PeriodicallyCheckingCode { get; set; }
        public string PeriodicallyCheckingName { get; set; }
        public string Description { get; set; }
        public string FileUrl { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string LastModifyUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductModel> ProductModel { get; set; }
    }
}
