//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlateFeeDetailModel
    {
        public System.Guid PlateFeeDetailId { get; set; }
        public Nullable<System.Guid> PlateFeeId { get; set; }
        public string Province { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual PlateFeeModel PlateFeeModel { get; set; }
    }
}
