//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPromotionContactModel
    {
        public System.Guid ProductPromotionContactId { get; set; }
        public Nullable<System.Guid> ProductPromotionDetailId { get; set; }
        public string ProfileAddress { get; set; }
        public Nullable<System.Guid> ContactId { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<bool> CheckAddress { get; set; }
        public Nullable<bool> CheckContact { get; set; }
    }
}
