//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPromotionDetailModel
    {
        public System.Guid ProductPromotionDetailId { get; set; }
        public Nullable<System.Guid> ProductPromotionId { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> Checker { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    }
}
