//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHierarchyModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductHierarchyModel()
        {
            this.MaterialModel = new HashSet<MaterialModel>();
        }
    
        public string ProductHierarchyCode { get; set; }
        public string ProductHierarchyName { get; set; }
        public Nullable<int> LevelNo { get; set; }
        public string ProfitCenterCode { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> Actived { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialModel> MaterialModel { get; set; }
    }
}
