//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileContactAttributeDeletedModel
    {
        public System.Guid ProfileId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string Position { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<bool> IsMain { get; set; }
    }
}
