//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileDeletedModel
    {
        public System.Guid ProfileId { get; set; }
        public int ProfileCode { get; set; }
        public string ProfileForeignCode { get; set; }
        public Nullable<bool> isForeignCustomer { get; set; }
        public string CustomerTypeCode { get; set; }
        public string Title { get; set; }
        public string ProfileName { get; set; }
        public string ProfileShortName { get; set; }
        public string AbbreviatedName { get; set; }
        public Nullable<int> DayOfBirth { get; set; }
        public Nullable<int> MonthOfBirth { get; set; }
        public Nullable<int> YearOfBirth { get; set; }
        public string Age { get; set; }
        public string Phone { get; set; }
        public string SAPPhone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string CountryCode { get; set; }
        public string SaleOfficeCode { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> WardId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string ImageUrl { get; set; }
        public string CreateByEmployee { get; set; }
        public string CreateAtCompany { get; set; }
        public string CreateAtSaleOrg { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public string CustomerAccountGroupCode { get; set; }
        public string CustomerGroupCode { get; set; }
        public string PaymentTermCode { get; set; }
        public string CustomerAccountAssignmentGroupCode { get; set; }
        public string CashMgmtGroupCode { get; set; }
        public string ReconcileAccountCode { get; set; }
        public string CustomerSourceCode { get; set; }
        public string TaxNo { get; set; }
        public string Website { get; set; }
        public string CustomerCareerCode { get; set; }
        public string CompanyNumber { get; set; }
        public string AddressTypeCode { get; set; }
        public Nullable<int> ProjectCode { get; set; }
        public string ProjectStatusCode { get; set; }
        public string QualificationLevelCode { get; set; }
        public string ProjectSourceCode { get; set; }
        public Nullable<System.Guid> ReferenceProfileId { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Dropdownlist1 { get; set; }
        public string Dropdownlist2 { get; set; }
        public string Dropdownlist3 { get; set; }
        public string Dropdownlist4 { get; set; }
        public string Dropdownlist5 { get; set; }
        public string Dropdownlist6 { get; set; }
        public string Dropdownlist7 { get; set; }
        public string Dropdownlist8 { get; set; }
        public string Dropdownlist9 { get; set; }
        public string Dropdownlist10 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public string ProjectLocation { get; set; }
        public Nullable<bool> IsAnCuongAccessory { get; set; }
        public string Laminate { get; set; }
        public string MFC { get; set; }
        public string Veneer { get; set; }
        public string Flooring { get; set; }
        public string Accessories { get; set; }
        public string KitchenEquipment { get; set; }
        public string OtherBrand { get; set; }
        public string HandoverFurniture { get; set; }
    }
}
