//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileEmailModel
    {
        public System.Guid EmailId { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
    
        public virtual ProfileModel ProfileModel { get; set; }
    }
}
