//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileLevelModel
    {
        public System.Guid CustomerLevelId { get; set; }
        public string CustomerLevelCode { get; set; }
        public string CustomerLevelName { get; set; }
        public Nullable<decimal> LineOfLevel { get; set; }
        public Nullable<decimal> ExchangeValue { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
    }
}
