//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileBAttributeModel
    {
        public System.Guid ProfileId { get; set; }
        public string TaxNo { get; set; }
        public string ContactName { get; set; }
        public string CompanyNumber { get; set; }
        public string Position { get; set; }
        public string CustomerCareerCode { get; set; }
        public string Website { get; set; }
    }
}
