//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile_Opportunity_CompetitorModel
    {
        public System.Guid OpportunityCompetitorId { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsWon { get; set; }
        public string CatalogCode { get; set; }
        public string MaterialCode { get; set; }
        public Nullable<decimal> ProjectValue { get; set; }
        public string MappingType { get; set; }
    
        public virtual ProfileModel ProfileModel { get; set; }
    }
}
