//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileModel()
        {
            this.AddressBookModel = new HashSet<AddressBookModel>();
            this.PartnerModel = new HashSet<PartnerModel>();
            this.PartnerModel1 = new HashSet<PartnerModel>();
            this.PersonInChargeModel = new HashSet<PersonInChargeModel>();
            this.Profile_File_Mapping = new HashSet<Profile_File_Mapping>();
            this.Profile_Opportunity_CompetitorModel = new HashSet<Profile_Opportunity_CompetitorModel>();
            this.Profile_Opportunity_InternalModel = new HashSet<Profile_Opportunity_InternalModel>();
            this.Profile_Opportunity_MaterialModel = new HashSet<Profile_Opportunity_MaterialModel>();
            this.Profile_Opportunity_PartnerModel = new HashSet<Profile_Opportunity_PartnerModel>();
            this.Profile_Opportunity_PartnerModel1 = new HashSet<Profile_Opportunity_PartnerModel>();
            this.ProfileEmailModel = new HashSet<ProfileEmailModel>();
            this.ProfileGroupModel = new HashSet<ProfileGroupModel>();
            this.DeliveryModel = new HashSet<DeliveryModel>();
            this.ProductWarrantyModel = new HashSet<ProductWarrantyModel>();
            this.ProfilePhoneModel = new HashSet<ProfilePhoneModel>();
            this.RoleInChargeModel = new HashSet<RoleInChargeModel>();
            this.StockReceivingMasterModel = new HashSet<StockReceivingMasterModel>();
            this.TemplateAndGiftMemberModel = new HashSet<TemplateAndGiftMemberModel>();
        }
    
        public System.Guid ProfileId { get; set; }
        public int ProfileCode { get; set; }
        public string ProfileForeignCode { get; set; }
        public Nullable<bool> isForeignCustomer { get; set; }
        public string CustomerTypeCode { get; set; }
        public string Title { get; set; }
        public string ProfileName { get; set; }
        public string ProfileShortName { get; set; }
        public string AbbreviatedName { get; set; }
        public Nullable<int> DayOfBirth { get; set; }
        public Nullable<int> MonthOfBirth { get; set; }
        public Nullable<int> YearOfBirth { get; set; }
        public string Age { get; set; }
        public string Phone { get; set; }
        public string SAPPhone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string CountryCode { get; set; }
        public string SaleOfficeCode { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> WardId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string ImageUrl { get; set; }
        public string CreateByEmployee { get; set; }
        public string CreateAtCompany { get; set; }
        public string CreateAtSaleOrg { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public string CustomerAccountGroupCode { get; set; }
        public string CustomerGroupCode { get; set; }
        public string PaymentTermCode { get; set; }
        public string CustomerAccountAssignmentGroupCode { get; set; }
        public string CashMgmtGroupCode { get; set; }
        public string ReconcileAccountCode { get; set; }
        public string CustomerSourceCode { get; set; }
        public string TaxNo { get; set; }
        public string Website { get; set; }
        public string CustomerCareerCode { get; set; }
        public string CompanyNumber { get; set; }
        public string AddressTypeCode { get; set; }
        public Nullable<int> ProjectCode { get; set; }
        public string ProjectStatusCode { get; set; }
        public string QualificationLevelCode { get; set; }
        public string ProjectSourceCode { get; set; }
        public Nullable<System.Guid> ReferenceProfileId { get; set; }
        public Nullable<decimal> ContractValue { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public string Dropdownlist1 { get; set; }
        public string Dropdownlist2 { get; set; }
        public string Dropdownlist3 { get; set; }
        public string Dropdownlist4 { get; set; }
        public string Dropdownlist5 { get; set; }
        public string Dropdownlist6 { get; set; }
        public string Dropdownlist7 { get; set; }
        public string Dropdownlist8 { get; set; }
        public string Dropdownlist9 { get; set; }
        public string Dropdownlist10 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public string ProjectLocation { get; set; }
        public Nullable<bool> IsAnCuongAccessory { get; set; }
        public string Laminate { get; set; }
        public string MFC { get; set; }
        public string Veneer { get; set; }
        public string Flooring { get; set; }
        public string Accessories { get; set; }
        public string KitchenEquipment { get; set; }
        public string OtherBrand { get; set; }
        public string HandoverFurniture { get; set; }
        public Nullable<bool> isCreateRequest { get; set; }
        public Nullable<System.DateTime> CreateRequestTime { get; set; }
        public Nullable<System.Guid> ReferenceProfileId2 { get; set; }
        public string PaymentMethodCode { get; set; }
        public string PartnerFunctionCode { get; set; }
        public string CurrencyCode { get; set; }
        public string TaxClassificationCode { get; set; }
        public string Manager { get; set; }
        public string DebsEmployee { get; set; }
        public string Text6 { get; set; }
        public string Text7 { get; set; }
        public string Text8 { get; set; }
        public string Text9 { get; set; }
        public string Text10 { get; set; }
        public Nullable<bool> IsThiCong { get; set; }
        public Nullable<bool> IsSyncedFromSAP { get; set; }
        public Nullable<bool> IsTopInvestor { get; set; }
        public Nullable<decimal> Number1 { get; set; }
        public Nullable<decimal> Number2 { get; set; }
        public Nullable<decimal> Number3 { get; set; }
        public Nullable<decimal> Number4 { get; set; }
        public Nullable<decimal> Number5 { get; set; }
        public Nullable<bool> IsInvestor { get; set; }
        public Nullable<bool> IsDesigner { get; set; }
        public Nullable<bool> IsContractor { get; set; }
        public Nullable<bool> AutoformatFullName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressBookModel> AddressBookModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerModel> PartnerModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerModel> PartnerModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonInChargeModel> PersonInChargeModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_File_Mapping> Profile_File_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Opportunity_CompetitorModel> Profile_Opportunity_CompetitorModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Opportunity_InternalModel> Profile_Opportunity_InternalModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Opportunity_MaterialModel> Profile_Opportunity_MaterialModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Opportunity_PartnerModel> Profile_Opportunity_PartnerModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profile_Opportunity_PartnerModel> Profile_Opportunity_PartnerModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileEmailModel> ProfileEmailModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileGroupModel> ProfileGroupModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryModel> DeliveryModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWarrantyModel> ProductWarrantyModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfilePhoneModel> ProfilePhoneModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleInChargeModel> RoleInChargeModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockReceivingMasterModel> StockReceivingMasterModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftMemberModel> TemplateAndGiftMemberModel { get; set; }
    }
}
