//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertiesProductModel
    {
        public System.Guid PropertiesId { get; set; }
        public System.Guid ProductId { get; set; }
        public string Subject { get; set; }
        public string SubjectColor { get; set; }
        public string Description { get; set; }
        public string DescriptionColor { get; set; }
        public string Image { get; set; }
        public string BackgroundColor { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
    
        public virtual ProductModel ProductModel { get; set; }
    }
}
