//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectModel
    {
        public System.Guid ProspectId { get; set; }
        public string ProspectCode { get; set; }
        public Nullable<int> ProspectType { get; set; }
        public string FullName { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ProspectAddress { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> WardId { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string EmailAddress { get; set; }
        public string Fax { get; set; }
        public string TaxCode { get; set; }
        public Nullable<bool> IsOpportunity { get; set; }
        public string Subject { get; set; }
        public Nullable<System.Guid> PurchasedTime { get; set; }
        public Nullable<decimal> EstimatedRevenue { get; set; }
        public Nullable<int> SuccessPercent { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.Guid> SourceId { get; set; }
        public string IdentityUrl { get; set; }
        public string UsedMaterial { get; set; }
        public string UsingMaterial { get; set; }
        public int GeneratedCode { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string SaleOrg { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> IdentityDate { get; set; }
        public string IdentityPlace { get; set; }
        public Nullable<System.Guid> Career { get; set; }
    }
}
