//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionBankModel
    {
        public System.Guid Id { get; set; }
        public int QuestionBankCode { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string AnswerC { get; set; }
        public string AnswerB { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> QuestionCategoryId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string TempDataImport { get; set; }
    
        public virtual AccountModel AccountModel { get; set; }
        public virtual AccountModel AccountModel1 { get; set; }
        public virtual CatalogModel CatalogModel { get; set; }
        public virtual CatalogModel CatalogModel1 { get; set; }
    }
}
