//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterReceiveNewsModel
    {
        public System.Guid RegisterReceiveNewsId { get; set; }
        public string CompanyCode { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public string DistrictName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
