//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RolesModel()
        {
            this.RoleInChargeModel = new HashSet<RoleInChargeModel>();
            this.MobileScreenPermissionModel = new HashSet<MobileScreenPermissionModel>();
            this.PagePermissionModel = new HashSet<PagePermissionModel>();
            this.AccountModel = new HashSet<AccountModel>();
        }
    
        public System.Guid RolesId { get; set; }
        public string RolesCode { get; set; }
        public string RolesName { get; set; }
        public Nullable<bool> isCheckLoginByTime { get; set; }
        public Nullable<bool> isEmployeeGroup { get; set; }
        public Nullable<System.DateTime> WorkingTimeFrom { get; set; }
        public Nullable<System.DateTime> WorkingTimeTo { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<bool> isSendSMSPermission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleInChargeModel> RoleInChargeModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileScreenPermissionModel> MobileScreenPermissionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagePermissionModel> PagePermissionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountModel> AccountModel { get; set; }
    }
}
