//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderDetailModel
    {
        public System.Guid SaleOrderDetailId { get; set; }
        public Nullable<System.Guid> SaleOrderMasterId { get; set; }
        public string AccessoryCode { get; set; }
        public string AccessoryName { get; set; }
        public string AccessoryTypeCode { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Plant { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual SaleOrderMasterModel SaleOrderMasterModel { get; set; }
    }
}
