//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchResultTemplateModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchResultTemplateModel()
        {
            this.SearchResultDetailTemplateModel = new HashSet<SearchResultDetailTemplateModel>();
        }
    
        public System.Guid SearchResultTemplateId { get; set; }
        public Nullable<bool> isSystem { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> PageId { get; set; }
        public string TemplateName { get; set; }
        public Nullable<bool> IsDefaultTemplate { get; set; }
        public string LayoutConfigs { get; set; }
        public string OrderBy { get; set; }
        public string TypeSort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchResultDetailTemplateModel> SearchResultDetailTemplateModel { get; set; }
    }
}
