//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchTemplateModel
    {
        public System.Guid SearchTemplateId { get; set; }
        public System.Guid AccountId { get; set; }
        public System.Guid PageId { get; set; }
        public string TemplateName { get; set; }
        public string SearchContent { get; set; }
    }
}
