//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderPoolModel
    {
        public System.Guid ServiceOrderPoolId { get; set; }
        public string ServiceOrderPoolCode { get; set; }
        public string ServiceOrderPoolName { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public bool Actived { get; set; }
    }
}
