//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceOrderModel()
        {
            this.ServiceOrderConsultModel = new HashSet<ServiceOrderConsultModel>();
            this.ServiceOrderDetailAccessoryModel = new HashSet<ServiceOrderDetailAccessoryModel>();
            this.ServiceOrderDetailServiceModel = new HashSet<ServiceOrderDetailServiceModel>();
        }
    
        public string SaleOrg { get; set; }
        public System.Guid ServiceOrderId { get; set; }
        public string ServiceOrderCode { get; set; }
        public string ServiceOrderTypeCode { get; set; }
        public string ServiceOrderName { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> SaleOrderMasterId { get; set; }
        public Nullable<System.Guid> VehicleId { get; set; }
        public string CustomerRequest { get; set; }
        public string KmDaDi { get; set; }
        public Nullable<int> WashRequest { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedAccountId { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.Guid> AccountId1TiepNhan { get; set; }
        public string SaleEmployee1Name { get; set; }
        public Nullable<System.DateTime> Step1DateTime { get; set; }
        public Nullable<System.DateTime> Step1DateTimeDuKien { get; set; }
        public string Step1Note { get; set; }
        public string ConsultNote { get; set; }
        public Nullable<System.Guid> AccountId1KyThuat1 { get; set; }
        public string SaleEmployee1aName { get; set; }
        public Nullable<System.Guid> AccountId1KyThuat2 { get; set; }
        public string SaleEmployee1bName { get; set; }
        public Nullable<System.Guid> AccountId2KiemTra { get; set; }
        public string SaleEmployee2Name { get; set; }
        public Nullable<System.DateTime> Step2DateTime { get; set; }
        public string Step2HangMuc { get; set; }
        public Nullable<System.Guid> Step2HangMucId { get; set; }
        public Nullable<System.DateTime> Step2NextDateTime { get; set; }
        public string Step2Km { get; set; }
        public Nullable<bool> Step2GetOldAccessory { get; set; }
        public Nullable<System.Guid> Step3AccountId { get; set; }
        public Nullable<System.DateTime> Step3DateTime { get; set; }
        public Nullable<System.Guid> AccountThuNgan { get; set; }
        public Nullable<int> Step { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string StoreName { get; set; }
        public string Category { get; set; }
        public string ServicePool { get; set; }
        public string LicensePlate { get; set; }
        public string SerialNumber { get; set; }
        public string EngineNumber { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string ProfitCenterCode { get; set; }
        public string ProductHierarchyCode { get; set; }
        public string MaterialGroupCode { get; set; }
        public string LaborCode { get; set; }
        public string MaterialFreightGroupCode { get; set; }
        public string ExternalMaterialGroupCode { get; set; }
        public string TemperatureConditionCode { get; set; }
        public string ContainerRequirementCode { get; set; }
        public Nullable<decimal> CurrentKilometers { get; set; }
        public string PersonnalNumberId { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Note { get; set; }
        public Nullable<bool> isUpdatedFromERP { get; set; }
        public Nullable<System.DateTime> UpdatedFromERPTime { get; set; }
        public string SystemNote { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public int GeneratedCode { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsSentToSap { get; set; }
        public string FullName { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<System.DateTime> IdentityDate { get; set; }
        public string IdentityPlace { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<System.Guid> WardId { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string EmailAddress { get; set; }
        public string Fax { get; set; }
        public string TaxCode { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.Guid> DeletedAccountId { get; set; }
        public Nullable<System.DateTime> DeletedDateTime { get; set; }
        public string SoBinhDien { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string DiscountNote { get; set; }
        public string DeletedNote { get; set; }
        public string SoThamChieu { get; set; }
    
        public virtual CustomerModel CustomerModel { get; set; }
        public virtual SaleOrderMasterModel SaleOrderMasterModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderConsultModel> ServiceOrderConsultModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderDetailAccessoryModel> ServiceOrderDetailAccessoryModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderDetailServiceModel> ServiceOrderDetailServiceModel { get; set; }
        public virtual VehicleInfoModel VehicleInfoModel { get; set; }
    }
}
