//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderConsultModel
    {
        public System.Guid ServiceOrderConsultId { get; set; }
        public Nullable<System.Guid> ServiceOrderId { get; set; }
        public string RequestMessage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<bool> IsThayThe { get; set; }
    
        public virtual ServiceOrderModel ServiceOrderModel { get; set; }
    }
}
