//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderTypeModel
    {
        public string ServiceOrderTypeCode { get; set; }
        public string ServiceOrderTypeName { get; set; }
        public Nullable<int> OrderIndex { get; set; }
    }
}
