//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSModel
    {
        public System.Guid SMSId { get; set; }
        public string SMSContent { get; set; }
        public string SMSTo { get; set; }
        public string ResponseText { get; set; }
        public Nullable<bool> isSent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string BrandName { get; set; }
        public string ErrorMessage { get; set; }
    }
}
