//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationsProductModel
    {
        public System.Guid SpecificationsProductId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid SpecificationsId { get; set; }
        public string Description { get; set; }
    
        public virtual ProductModel ProductModel { get; set; }
        public virtual SpecificationsModel SpecificationsModel { get; set; }
    }
}
