//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsModel
    {
        public System.Guid SponsId { get; set; }
        public string Descriptions { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
    }
}
