//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTransition_Task_Mapping
    {
        public System.Guid TaskTransitionLogId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.Guid> FromStatusId { get; set; }
        public Nullable<System.Guid> ToStatusId { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveTime { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<decimal> Number1 { get; set; }
    }
}
