//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTransitionModel
    {
        public System.Guid StatusTransitionId { get; set; }
        public string TransitionName { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> WorkFlowId { get; set; }
        public Nullable<System.Guid> FromStatusId { get; set; }
        public Nullable<System.Guid> ToStatusId { get; set; }
        public Nullable<bool> isAssigneePermission { get; set; }
        public Nullable<bool> isReporterPermission { get; set; }
        public string Color { get; set; }
        public Nullable<bool> isRequiredComment { get; set; }
        public Nullable<bool> isCreateUserPermission { get; set; }
        public string StatusTransitionIn { get; set; }
        public string StatusTransitionOut { get; set; }
        public Nullable<bool> isAutomaticTransitions { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> BranchPositionLeft { get; set; }
        public Nullable<int> BranchPositionRight { get; set; }
        public string BranchIn { get; set; }
        public string BranchOut { get; set; }
        public string unsignedBranchName { get; set; }
    
        public virtual TaskStatusModel TaskStatusModel { get; set; }
        public virtual TaskStatusModel TaskStatusModel1 { get; set; }
        public virtual WorkFlowModel WorkFlowModel { get; set; }
    }
}
