//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnHand
    {
        public System.Guid ProductId { get; set; }
        public string ERPProductCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
    }
}
