//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyModel
    {
        public System.Guid SurveyId { get; set; }
        public string Question { get; set; }
        public string Type { get; set; }
        public int SurveyCode { get; set; }
    }
}
