//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskProductUsualErrorModel
    {
        public System.Guid TaskProductUsualErrorId { get; set; }
        public Nullable<System.Guid> TaskProductId { get; set; }
        public string UsualErrorCode { get; set; }
    
        public virtual TaskProductModel TaskProductModel { get; set; }
    }
}
