//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskProductAccessoryModel
    {
        public System.Guid TaskProductAccessoryId { get; set; }
        public Nullable<System.Guid> TaskProductId { get; set; }
        public Nullable<System.Guid> AccessoryId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ProductAccessoryTypeCode { get; set; }
        public string AccErrorTypeCode { get; set; }
    
        public virtual TaskProductModel TaskProductModel { get; set; }
    }
}
