//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskModel()
        {
            this.Task_File_Mapping = new HashSet<Task_File_Mapping>();
            this.TaskProductModel = new HashSet<TaskProductModel>();
        }
    
        public System.Guid TaskId { get; set; }
        public int TaskCode { get; set; }
        public string Summary { get; set; }
        public Nullable<System.Guid> ProfileId { get; set; }
        public string Description { get; set; }
        public string PriorityCode { get; set; }
        public System.Guid WorkFlowId { get; set; }
        public System.Guid TaskStatusId { get; set; }
        public Nullable<System.Guid> ProductWarrantyId { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EstimateEndDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid StoreId { get; set; }
        public string Reporter { get; set; }
        public string ServiceTechnicalTeamCode { get; set; }
        public string CustomerReviews { get; set; }
        public Nullable<System.Guid> ConstructionUnit { get; set; }
        public string FileUrl { get; set; }
        public string CommonMistakeCode { get; set; }
        public Nullable<int> DateKey { get; set; }
        public string ErrorTypeCode { get; set; }
        public string ErrorCode { get; set; }
        public Nullable<bool> isRequiredCheckin { get; set; }
        public string VisitAddress { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string VisitSaleOfficeCode { get; set; }
        public string VisitTypeCode { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> DeleteBy { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isPrivate { get; set; }
        public Nullable<bool> isRemind { get; set; }
        public Nullable<int> RemindTime { get; set; }
        public string RemindCycle { get; set; }
        public Nullable<bool> isRemindForReporter { get; set; }
        public Nullable<bool> isRemindForAssignee { get; set; }
        public Nullable<System.DateTime> RemindStartDate { get; set; }
        public string Property1 { get; set; }
        public string Property2 { get; set; }
        public Nullable<decimal> Property3 { get; set; }
        public string Property4 { get; set; }
        public string Property5 { get; set; }
        public Nullable<System.Guid> ParentTaskId { get; set; }
        public string SalesSupervisorCode { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public string ProfileAddress { get; set; }
        public Nullable<bool> IsAssignGroup { get; set; }
        public Nullable<bool> IsSync { get; set; }
        public Nullable<int> TaskTempCode { get; set; }
        public Nullable<decimal> Property6 { get; set; }
        public string SubtaskCode { get; set; }
        public string CancelReason { get; set; }
        public Nullable<System.Guid> ConstructionUnitContact { get; set; }
        public string ShortNote { get; set; }
        public string VisitPlace { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public Nullable<System.Guid> WardId { get; set; }
        public Nullable<System.Guid> DistrictId { get; set; }
        public Nullable<bool> IsTogether { get; set; }
        public Nullable<System.Guid> GoogleEventId { get; set; }
        public Nullable<bool> HasSurvey { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_File_Mapping> Task_File_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProductModel> TaskProductModel { get; set; }
    }
}
