//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskProductModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskProductModel()
        {
            this.TaskProductAccessoryModel = new HashSet<TaskProductAccessoryModel>();
            this.TaskProductUsualErrorModel = new HashSet<TaskProductUsualErrorModel>();
        }
    
        public System.Guid TaskProductId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public string WarrantyProductTypeCode { get; set; }
        public string ErrorTypeCode { get; set; }
        public string ErrorCode { get; set; }
        public string ProductLevelCode { get; set; }
        public string ProductColorCode { get; set; }
        public string ProductCategoryCode { get; set; }
        public string Unit { get; set; }
        public string SAPSOWarranty { get; set; }
        public string SAPSOProduct { get; set; }
        public Nullable<decimal> ProductValue { get; set; }
        public Nullable<decimal> WarrantyValue { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual TaskModel TaskModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProductAccessoryModel> TaskProductAccessoryModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskProductUsualErrorModel> TaskProductUsualErrorModel { get; set; }
    }
}
