//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatusModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskStatusModel()
        {
            this.StatusTransitionModel = new HashSet<StatusTransitionModel>();
            this.StatusTransitionModel1 = new HashSet<StatusTransitionModel>();
            this.Kanban_TaskStatus_Mapping = new HashSet<Kanban_TaskStatus_Mapping>();
        }
    
        public System.Guid TaskStatusId { get; set; }
        public string TaskStatusName { get; set; }
        public Nullable<System.Guid> WorkFlowId { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string TaskStatusCode { get; set; }
        public string ProcessCode { get; set; }
        public string Category { get; set; }
        public Nullable<int> PositionLeft { get; set; }
        public Nullable<int> PositionRight { get; set; }
        public Nullable<bool> AutoUpdateEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusTransitionModel> StatusTransitionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusTransitionModel> StatusTransitionModel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kanban_TaskStatus_Mapping> Kanban_TaskStatus_Mapping { get; set; }
        public virtual WorkFlowModel WorkFlowModel { get; set; }
    }
}
