//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Event_Mapping
    {
        public System.Guid TaskEventMappingId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public string EventId { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
