//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateAndGiftTargetGroupModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateAndGiftTargetGroupModel()
        {
            this.TemplateAndGiftCampaignModel = new HashSet<TemplateAndGiftCampaignModel>();
            this.TemplateAndGiftMemberModel = new HashSet<TemplateAndGiftMemberModel>();
        }
    
        public System.Guid Id { get; set; }
        public int TargetGroupCode { get; set; }
        public string TargetGroupName { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftCampaignModel> TemplateAndGiftCampaignModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemplateAndGiftMemberModel> TemplateAndGiftMemberModel { get; set; }
        public virtual AccountModel AccountModel { get; set; }
        public virtual AccountModel AccountModel1 { get; set; }
    }
}
