//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferModel
    {
        public System.Guid TransferId { get; set; }
        public int TransferCode { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public string SalesEmployeeCode { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedTime { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string SenderName { get; set; }
        public string SenderPhone { get; set; }
        public string RecipientName { get; set; }
        public string RecipientPhone { get; set; }
        public string RecipientAddress { get; set; }
        public string RecipientCompany { get; set; }
        public string SenderAddress { get; set; }
        public string DeletedReason { get; set; }
        public Nullable<System.Guid> StockTransferRequestId { get; set; }
    
        public virtual CompanyModel CompanyModel { get; set; }
        public virtual SalesEmployeeModel SalesEmployeeModel { get; set; }
        public virtual StoreModel StoreModel { get; set; }
    }
}
