//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleInfoModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleInfoModel()
        {
            this.AccessorySaleOrderModel = new HashSet<AccessorySaleOrderModel>();
            this.ServiceOrderModel = new HashSet<ServiceOrderModel>();
        }
    
        public System.Guid VehicleId { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public string LicensePlate { get; set; }
        public string SerialNumber { get; set; }
        public string EngineNumber { get; set; }
        public Nullable<decimal> CurrentKilometers { get; set; }
        public string WarrantyNumber { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public string SaleOrg { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ProfitCenterCode { get; set; }
        public string ProductHierarchyCode { get; set; }
        public string SoBinhDien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessorySaleOrderModel> AccessorySaleOrderModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderModel> ServiceOrderModel { get; set; }
    }
}
