//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Profile_ContactPhone
    {
        public Nullable<System.Guid> CompanyId { get; set; }
        public System.Guid ProfileId { get; set; }
        public string Phone { get; set; }
        public int ProfileCode { get; set; }
        public string ProfileName { get; set; }
        public string Email { get; set; }
        public string DepartmentName { get; set; }
        public string PositionName { get; set; }
    }
}
