//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Task_GTB
    {
        public System.Guid TaskId { get; set; }
        public int TaskCode { get; set; }
        public string Summary { get; set; }
        public Nullable<System.Guid> ChildTaskId { get; set; }
        public Nullable<int> ChildTaskCode { get; set; }
        public string ChildTaskSummary { get; set; }
        public string ChildTaskDescription { get; set; }
        public string AssigneeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RemindDate { get; set; }
    }
}
