//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Stock_TransferFrom_Delivery
    {
        public Nullable<System.Guid> StockId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public int ReceiveQty { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
    }
}
