//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Profile_Address
    {
        public Nullable<System.Guid> ProfileId { get; set; }
        public string Address { get; set; }
        public Nullable<System.Guid> ProvinceId { get; set; }
        public System.Guid AreaId { get; set; }
    }
}
