//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowConfigModel
    {
        public System.Guid WorkFlowId { get; set; }
        public string FieldCode { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string Parameters { get; set; }
        public string Note { get; set; }
        public Nullable<bool> HideWhenAdd { get; set; }
        public string AddDefaultValue { get; set; }
        public Nullable<bool> HideWhenEdit { get; set; }
        public string EditDefaultValue { get; set; }
    }
}
