//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingDateModel
    {
        public System.Guid WorkingDateId { get; set; }
        public System.Guid StoreId { get; set; }
        public System.DateTime DayOff { get; set; }
    }
}
