//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkFlowModel()
        {
            this.StatusTransitionModel = new HashSet<StatusTransitionModel>();
            this.TaskStatusModel = new HashSet<TaskStatusModel>();
        }
    
        public System.Guid WorkFlowId { get; set; }
        public string WorkFlowCode { get; set; }
        public string WorkFlowName { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public Nullable<bool> Actived { get; set; }
        public string WorkflowCategoryCode { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<bool> IsDisabledSummary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusTransitionModel> StatusTransitionModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskStatusModel> TaskStatusModel { get; set; }
    }
}
