//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingTimeDetailModel
    {
        public System.Guid WorkingTimeDetailId { get; set; }
        public Nullable<System.Guid> WorkingTimeId { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.TimeSpan> TimeFrameFrom { get; set; }
        public Nullable<System.TimeSpan> TimeFrameTo { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual WorkingTimeModel WorkingTimeModel { get; set; }
    }
}
