//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.WinForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentModel
    {
        public System.Guid Id { get; set; }
        public int ContentCode { get; set; }
        public string Type { get; set; }
        public string ContentName { get; set; }
        public System.Guid FromEmailAccountId { get; set; }
        public string SentFrom { get; set; }
        public string SenderName { get; set; }
        public string CompanyCode { get; set; }
        public string SaleOrg { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string CatalogCode { get; set; }
        public string EmailType { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
    }
}
