//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.WinForm.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SendMailCalendarEntityDataContext : DbContext
    {
        public SendMailCalendarEntityDataContext()
            : base("name=SendMailCalendarEntityDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProfileModel> ProfileModel { get; set; }
        public virtual DbSet<CampaignModel> CampaignModel { get; set; }
        public virtual DbSet<MailServerProviderModel> MailServerProviderModel { get; set; }
        public virtual DbSet<MemberOfExternalProfileTargetGroupModel> MemberOfExternalProfileTargetGroupModel { get; set; }
        public virtual DbSet<MemberOfTargetGroupModel> MemberOfTargetGroupModel { get; set; }
        public virtual DbSet<TargetGroupModel> TargetGroupModel { get; set; }
        public virtual DbSet<Unfollow> Unfollow { get; set; }
        public virtual DbSet<CatalogModel> CatalogModel { get; set; }
        public virtual DbSet<SendMailCalendarModel> SendMailCalendarModel { get; set; }
        public virtual DbSet<ContentModel> ContentModel { get; set; }
        public virtual DbSet<EmailAccountModel> EmailAccountModel { get; set; }
    }
}
