//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.WinForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMailCalendarModel
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CampaignId { get; set; }
        public Nullable<System.Guid> ToProfileId { get; set; }
        public string ToEmail { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public string Param { get; set; }
        public Nullable<bool> IsBounce { get; set; }
        public Nullable<bool> IsOpened { get; set; }
        public Nullable<bool> isConfirm { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<bool> isCheckin { get; set; }
        public Nullable<System.DateTime> CheckinTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<bool> isError { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> LastOpenedTime { get; set; }
        public Nullable<int> NumberOfParticipant { get; set; }
    }
}
