//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISD.WinForm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetGroupModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TargetGroupModel()
        {
            this.MemberOfExternalProfileTargetGroupModel = new HashSet<MemberOfExternalProfileTargetGroupModel>();
            this.MemberOfTargetGroupModel = new HashSet<MemberOfTargetGroupModel>();
        }
    
        public System.Guid Id { get; set; }
        public int TargetGroupCode { get; set; }
        public string TargetGroupName { get; set; }
        public System.Guid CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.Guid> LastEditBy { get; set; }
        public bool Actived { get; set; }
        public Nullable<System.DateTime> LastEditTime { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberOfExternalProfileTargetGroupModel> MemberOfExternalProfileTargetGroupModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberOfTargetGroupModel> MemberOfTargetGroupModel { get; set; }
    }
}
